# Generated by Django 4.2.8 on 2024-01-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='deleted',
        ),
    ]
