# Generated by Django 4.2.8 on 2023-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_category_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_category',
            name='image',
            field=models.ImageField(upload_to='main_category'),
        ),
    ]
