# Generated by Django 5.0.1 on 2024-01-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_category_app', '0005_alter_main_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='category_offer',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main_category',
            name='category_offer_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
