# Generated by Django 4.2.8 on 2023-12-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_customuser_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_profile_image',
        ),
    ]
