# Generated by Django 4.2.8 on 2023-12-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
