# Generated by Django 5.0.1 on 2024-01-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='refferal',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
