# Generated by Django 4.2.8 on 2024-01-01 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('house_no', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=150)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
