# Generated by Django 4.2.8 on 2023-12-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='status',
        ),
    ]
