# Generated by Django 4.2.8 on 2023-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_games_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='image',
            field=models.ImageField(default=1, upload_to='sub_category'),
            preserve_default=False,
        ),
    ]
