# Generated by Django 4.2.8 on 2023-12-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_games_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show,1-hidden'),
        ),
    ]
