# Generated by Django 5.0.1 on 2024-01-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_games_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='img',
            field=models.ImageField(default=0, upload_to='prod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='product_offer',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
