# Generated by Django 5.0.1 on 2024-01-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_games_img_games_product_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='product_offer',
            new_name='sub_offer',
        ),
    ]
