# Generated by Django 5.0.1 on 2024-01-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_rename_product_offer_games_sub_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='sub_offer',
        ),
    ]
