# Generated by Django 5.0.1 on 2024-02-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_remove_games_sub_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='img',
        ),
    ]
