# Generated by Django 5.0.1 on 2024-01-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
