# Generated by Django 5.0.1 on 2024-01-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
