# Generated by Django 5.0.1 on 2024-01-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
