# Generated by Django 5.0.1 on 2024-01-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
