# Generated by Django 5.0.1 on 2024-01-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
