# Generated by Django 5.0.1 on 2024-01-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
